services:
  lemiro:
    build: .
    image: lemiro/lemiro:latest
    container_name: lemiro
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/.next
      - public:/app/public
    env_file:
      - .env
      - .env.local