import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { getMenuItems } from '@/utils/menu';

const iranFont = localFont({
  src: './fonts/IRAN.woff',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = await getMenuItems();
  return (
    <html lang="fa">
      <body className={`${iranFont.className} antialiased`}>
        <Navbar menuItems={menuItems} />
        <div className="flex bg-gray-50 relative z-10 justify-center">
          <div className="flex min-h-svh w-full justify-center">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
